---
title: "06 - Clonal Overlap (TRB)"
author: "Teresa Rubio"
date: "March, 2021"
output: html_document
---

# Packages
```{r, message=FALSE}
library(immunarch)
library(NMF)
library(ggplot2)
```

# Work enviroment
```{r}
# Define input/output directories
inputDir <- "~/MHE_TCR/02_DataFiltering"
outputDir <- "~/MHE_TCR/TCRanalysis_bookdown"
articleDir <- "~/MHE_TCR/TCRanalysis_articlefigures"

# Load sample info
SampleInfo <- read.csv("samplesinfo.csv", check.names = F)
SampleInfo$Group <- factor(SampleInfo$Group, levels = unique(SampleInfo$Group))
groups_color <- c("#56B4E9", "red", "black")

outDir <- "~/ClusterCIPF/TCRanalysis_withoutoutliers/TCRanalysis_bookdown"
currentDir <- "~/ClusterCIPF/TCRanalysis_withoutoutliers/05_ClonalExpansion"
  
chain <- "TRB"
```


# Clonal Persistence (Overlap)
## Jaccard similarity
```{r, message=FALSE}
# Processed MiXCR data
immdata <- immunarch::repLoad(file.path(inputDir, paste0("clones_",chain,"_filtered")))

# Jaccard similarity
imm_ov2 <- immunarch::repOverlap(immdata$data, .method = "jaccard", .verbose = F)

# Plot
jaccard <- immunarch::vis(imm_ov2, .text.size = 2.5, .signif.digits = 1, .title = "CDR3 overlap (jaccard)")
jaccard

# Jaccard mean+-stderr
round(mean(imm_ov2, na.rm = T), 5)
round(sd(imm_ov2, na.rm = T), 5)
stderr <- function(x, na.rm=FALSE) {
  if (na.rm) x <- na.omit(x)
  sqrt(var(x)/length(x)) # == sd(x)/sqrt(length(x))
}
round(stderr(c(imm_ov2), na.rm = T), 5)
```

# Report plots
```{r, results='hide'}
png(file.path(outputDir, "06_overlap_jaccard.png"), height = 30, width = 30, units = "cm", res = 300)
jaccard
dev.off()
```

# Article figure
```{r, results='hide'}
png(file.path(articleDir, "Figure2A.png"), height = 30, width = 30, units = "cm", res = 300)
jaccard
dev.off()
```

