---
title: "07 - k-mer analysis (TRB)"
author: "Teresa Rubio"
date: "March, 2021"
output: html_document
---

# Packages
```{r, message=FALSE}
library(immunarch)
library(NMF)
library(RcmdrMisc)
library(viridis)
```

# Work enviroment
```{r}
# Define input/output directories
inputDir <- "~/MHE_TCR/02_DataFiltering"
outputDir <- "~/MHE_TCR/TCRanalysis_bookdown"
articleDir <- "~/MHE_TCR/TCRanalysis_articlefigures"

# Load sample info
SampleInfo <- read.csv("samplesinfo.csv", check.names = F)
SampleInfo$Group <- factor(SampleInfo$Group, levels = unique(SampleInfo$Group))
groups_color <- c("#56B4E9", "red", "black")

chain <- "TRB"
```

# List of repertoires
```{r}
# Filtered (reads > 1) MiXCR data
immdata <- immunarch::repLoad(file.path(inputDir, paste0("clones_",chain,"_filtered")))
```

# 3-mers (k=3)
```{r, message=FALSE, results='hide'}
# k-mer matrix across samples
kmers <- getKmers(immdata$data, .k=3)
kmers <- data.frame(kmers)
rownames(kmers) <- kmers$Kmer
kmers <- kmers[,-1]
kmers[is.na(kmers)] <- 0

# Heatmap
color_df <- data.frame(Group = SampleInfo$Group)

png(file.path(outputDir, "07_kmers_pearson.png"), height = 20, width = 23, units = "cm", res = 300)
NMF::aheatmap(cor(kmers, method = "pearson", use = "complete.obs"),
              color = viridis::magma(100),
              main = "Kmers - Pearson Correlation",
              cexRow = 0.5,
              annCol = color_df,
              annRow = color_df,
              annColors = list(groups_color))
dev.off()

png(file.path(outputDir, "07_kmers_spearman.png"), height = 20, width = 23, units = "cm", res = 300)
NMF::aheatmap(cor(kmers, method = "spearman", use = "complete.obs"),
              color = viridis::magma(100),
              main = "Kmers - Spearman Correlation",
              cexRow = 0.5,
              annCol = color_df,
              annRow = color_df,
              annColors = list(groups_color))
dev.off()
```

# Test correlation significance
```{r}
# ++++++++++++++++++++++++++++
# flattenCorrMatrix
# ++++++++++++++++++++++++++++
# cormat : matrix of the correlation coefficients
# pmat : matrix of the correlation p-values
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

res3 <- RcmdrMisc::rcorr.adjust(as.matrix(kmers), type="pearson")
cormatrix <- flattenCorrMatrix(res3$R$r, res3$R$P)
cormatrix$cor <- round(cormatrix$cor, 3)
write.table(cormatrix, file = file.path(outputDir, "07_kmers_TRB_corrmatrix.csv"), 
            sep = ",", row.names = F, col.names = T, quote = F)
```

# Article figure
```{r, results='hide'}
png(file.path(articleDir, "Figure2C.png"), height = 20, width = 23, units = "cm", res = 300)
NMF::aheatmap(cor(kmers, method = "pearson", use = "complete.obs"),
              color = viridis::magma(100),
              main = "Kmers - Pearson Correlation",
              cexRow = 0.5,
              annCol = color_df,
              annRow = color_df,
              annColors = list(groups_color))
dev.off()
```
